[PHP]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Error Handling
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Resource Limits
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 36M
max_execution_time = 30
max_input_time = 60
max_input_vars = 3000
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Date / Time
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
date.timezone = Europe/London
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Security
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
expose_php = Off
session.cookie_httponly = 1
session.cookie_secure = 0
session.use_strict_mode = 1
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Performance
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
realpath_cache_size = 4096K
realpath_cache_ttl = 600
pcre.jit = 1
